// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDks0BSX8QVe-WvM12a5sAf6xshzqqTawY',
    appId: '1:718561497000:web:e4509d287048b831c0579d',
    messagingSenderId: '718561497000',
    projectId: 'laindain-d9734',
    authDomain: 'laindain-d9734.firebaseapp.com',
    storageBucket: 'laindain-d9734.appspot.com',
    measurementId: 'G-BTQD7YPDF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGHlz0kwt3m0ZFshSQiLA7nS-ASo75xU',
    appId: '1:718561497000:android:27e26b93608be984c0579d',
    messagingSenderId: '718561497000',
    projectId: 'laindain-d9734',
    storageBucket: 'laindain-d9734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgw6fPxb5YphUkrAiN3JN7BZH2M78vSB4',
    appId: '1:718561497000:ios:ae5c6f70c95bd200c0579d',
    messagingSenderId: '718561497000',
    projectId: 'laindain-d9734',
    storageBucket: 'laindain-d9734.appspot.com',
    androidClientId: '718561497000-nbcfu6h76t5in9d6nul4tgoh20k1o1cj.apps.googleusercontent.com',
    iosClientId: '718561497000-278kuq84qu89apcphafgn9bflfb0r3ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.lainDain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgw6fPxb5YphUkrAiN3JN7BZH2M78vSB4',
    appId: '1:718561497000:ios:ae5c6f70c95bd200c0579d',
    messagingSenderId: '718561497000',
    projectId: 'laindain-d9734',
    storageBucket: 'laindain-d9734.appspot.com',
    androidClientId: '718561497000-nbcfu6h76t5in9d6nul4tgoh20k1o1cj.apps.googleusercontent.com',
    iosClientId: '718561497000-278kuq84qu89apcphafgn9bflfb0r3ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.lainDain',
  );
}
